---
# tasks file for apache2

- name: install apache2 latest
  apt: name=apache2 state=latest
  when: ansible_os_family=="Debian"

- name: copy the apache2 config file and restart apache2
  template:
    src:  apache2.conf.j2
    dest: /etc/apache2/apache2.conf
  notify:
   - apache2

- name: copy the ports file
  template:
    src:  ports.conf.j2
    dest: /etc/apache2/ports.conf


