version: '3'
services:
  fluentd:
    build: ./fluentd
    links: 
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
  kibana:
    image: kibana:5.6
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"

